[tool.poetry]
name = "PeptideMind"
version = "0.1.0"
description = ""
authors = ["David Handler <david.handler@students.mq.edu.au>"]

[tool.poetry.dependencies]
python = "^3.6"
matplotlib = "==2.1.0"
pandas = "==0.21.0"
numpy = "==1.17.5"
scikit_learn = "==0.22"
scipy = "==1.3.1"